### ISSUE TITLE
upgrade react-select

### ISSUE THREAD

**Issue by dajohi** [decred/pi-ui#264]
```
PASS src/components/Select/test/select.test.js
  ��� Console

    console.warn
      Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
      
      * Move data fetching code or side effects to componentDidUpdate.
      * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
      * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
      
      Please update the following components: Select

      at printWarning (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:120:30)
      at warn (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:83:5)
      at Object.<anonymous>.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2154:7)
      at flushRenderPhaseStrictModeWarningsInDEV (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13604:31)
      at commitRootImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12888:3)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1775:10)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12873:3)

    console.warn
      Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
      
      * Move data fetching code or side effects to componentDidUpdate.
      * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
      * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
      
      Please update the following components: Select

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at warn (node_modules/react-dom/cjs/react-dom.development.js:51:5)
      at Object.<anonymous>.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings (node_modules/react-dom/cjs/react-dom.development.js:11377:7)
      at flushRenderPhaseStrictModeWarningsInDEV (node_modules/react-dom/cjs/react-dom.development.js:23112:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22396:3)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22381:3)
```

**Comment by tiagoalvesdulce** [comment]
We are considering if we update or drop `react-select`.

**Comment by vctt94** [comment]
Talking with @amassarwi about this issue, and I think it would be better dropping react-select.

As he mentioned, many dependencies are built without external-dep, and keeping dependencies updated is a pain. 

So I think design our own select would be a good choice here. 

Thoughts on that @tiagoalvesdulce ?

**Comment by tiagoalvesdulce** [comment]
I agree. We will implementing a new Select component after the next politeia release.

**Comment by guilhermemntt** [comment]
I've just talked with @tiagoalvesdulce and I'll carry out the development of our new select component.
